version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: plancraft
      MYSQL_USER: huy
      MYSQL_PASSWORD: huy123
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: huy
      DB_PASSWORD: huy123
      DB_NAME: plancraft
    command: sh -c "sleep 10 && npm run init"


volumes:
  db-data:
